# Generated by Django 4.0.6 on 2022-08-03 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rps_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(3)])),
                ('win_condition', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('throw', models.CharField(max_length=8, validators=[rps_app.models.validate_throw])),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_instructor',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='appuser',
            name='games',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='rps_app.game'),
        ),
    ]
