# Generated by Django 4.0.6 on 2022-08-03 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_app', '0002_game_throw_remove_vote_choice_remove_vote_poll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='win_condition',
        ),
        migrations.AddField(
            model_name='game',
            name='total_throws',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='victory_num',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
